model: cnn1d

# 数据集
data_path: datasets/CASIA  # 数据集路径
class_labels: ["angry", "fear", "happy", "neutral", "sad", "surprise"]  # 情感标签
person_labels: ["liuchanhg", "wangzhe", "zhaoquanyin", "ZhaoZuoxiang"] # 人物名称

# 特征
feature_folder: features\6-category\feature\  # 特征存储文件夹

# checkpoints
checkpoint_path: checkpoints/  # checkpoint 存储路径
checkpoint_name: CNN1D  # checkpoint 文件名

# 训练参数
epochs: 100  # 训练 epoch 数
batch_size: 30  # 批大小
lr: 0.001  # 学习率

# 模型参数
n_kernels: 32  # 卷积核数量（每个卷积层都一样）
kernel_sizes: [5, 5]  # 每个卷积层的卷积核大小，列表长度为卷积层数量
dropout: 0.5
hidden_size: 32
